// Environment endpoints for the frontend.
// Generated by scripts/apply-config.sh from config.values — you can also edit
// the placeholders directly for a quick test. Cognito IDs are public (not secrets).
export const env = {
  region: "us-east-1",
  cognito: {
    userPoolId: "us-east-1_XXXXXXXXX",
    clientId: "XXXXXXXXXXXXXXXXXXXXXXXXXX",
  },
  apiBaseUrl: "/api",
};
export default env;
