#!/bin/bash
# ============================================================================
#  Reads config.values (the single source) and writes the real source files:
#    - src/config/env.js   (frontend: region + cognito + api base) [committed]
#    - api/.env            (backend: db creds + cognito)            [gitignored]
#  Usage:  bash scripts/apply-config.sh
# ============================================================================
set -e
cd "$(dirname "$0")/.."

if [ ! -f config.values ]; then
  echo "config.values not found. Copy config.values.example -> config.values and fill it."
  exit 1
fi

set -a; source config.values; set +a

# ---- frontend (Cognito IDs are public, safe to commit) ----
mkdir -p src/config
cat > src/config/env.js <<EOF
// AUTO-GENERATED by scripts/apply-config.sh — DO NOT EDIT.
// Change config.values, then re-run the script.
export const env = {
  region: "${AWS_REGION}",
  cognito: {
    userPoolId: "${COGNITO_USER_POOL_ID}",
    clientId: "${COGNITO_CLIENT_ID}",
  },
  apiBaseUrl: "${API_BASE_URL:-/api}",
};
export default env;
EOF
echo "wrote src/config/env.js"

# ---- backend (.env holds the DB password — gitignored) ----
mkdir -p api
cat > api/.env <<EOF
AWS_REGION=${AWS_REGION}
COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT:-3306}
DB_NAME=${DB_NAME:-school_app}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
EOF
echo "wrote api/.env"
echo "Done. Commit src/config/env.js and push, then redeploy."
