#!/bin/bash
# =============================================================================
# scripts/setup-env.sh
# Pulls CloudFormation stack outputs and generates config.values + .env files.
# Run once after deploy: sudo bash scripts/setup-env.sh
# Only requires you to type the DB password — everything else is auto-detected.
# =============================================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== Vidyam Environment Setup ==="

# ── Auto-detect region from instance metadata ─────────────────────────────
REGION=$(curl -sf http://169.254.169.254/latest/meta-data/placement/region)
if [ -z "$REGION" ]; then
  echo "ERROR: Could not detect AWS region from instance metadata."
  exit 1
fi
echo "Region: $REGION"

# ── Auto-detect stack name from EC2 tags (CloudFormation sets this tag) ───
INSTANCE_ID=$(curl -sf http://169.254.169.254/latest/meta-data/instance-id)
STACK_NAME=$(aws ec2 describe-tags \
  --region "$REGION" \
  --filters "Name=resource-id,Values=$INSTANCE_ID" \
            "Name=key,Values=aws:cloudformation:stack-name" \
  --query 'Tags[0].Value' \
  --output text 2>/dev/null)

if [ -z "$STACK_NAME" ] || [ "$STACK_NAME" = "None" ]; then
  read -p "Could not auto-detect stack name. Enter CFN stack name: " STACK_NAME
fi
echo "Stack: $STACK_NAME"

# ── Helper: pull a single output from the stack ───────────────────────────
get_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

echo "Fetching stack outputs..."
RDS_HOST=$(get_output "RDSEndpoint")
COGNITO_POOL_ID=$(get_output "CognitoUserPoolId")
COGNITO_CLIENT_ID=$(get_output "CognitoAppClientId")

if [ -z "$RDS_HOST" ]; then
  echo "ERROR: Could not fetch RDSEndpoint from stack. Is the stack CREATE_COMPLETE?"
  exit 1
fi

echo "  RDS Endpoint    : $RDS_HOST"
echo "  Cognito Pool ID : $COGNITO_POOL_ID"
echo "  Cognito Client  : $COGNITO_CLIENT_ID"

# ── Prompt for DB password only ───────────────────────────────────────────
echo ""
read -s -p "Enter RDS DB password (input hidden): " DB_PASSWORD
echo ""

# ── Write config.values (used by apply-config.sh) ─────────────────────────
cat > "$APP_DIR/config.values" <<EOF
# AUTO-GENERATED by scripts/setup-env.sh — do not edit manually.
# Re-run this script to refresh values.

AWS_REGION=$REGION
COGNITO_USER_POOL_ID=$COGNITO_POOL_ID
COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
DB_HOST=$RDS_HOST
DB_PORT=3306
DB_NAME=school_app
DB_USER=vidyam_admin
DB_PASSWORD=$DB_PASSWORD
API_BASE_URL=/api
EOF
echo "✓ Written config.values"

# ── Run apply-config.sh to write api/.env and src/config/env.js ───────────
bash "$SCRIPT_DIR/apply-config.sh"

echo ""
echo "=== Setup complete ==="
echo "Next steps:"
echo "  1. cd $APP_DIR && npm install && npm run build"
echo "  2. cd api && npm install"
echo "  3. pm2 start server.js --name vidyam-api && pm2 save"
echo "  4. Configure Nginx and run: systemctl start nginx"
